---

- name: Enable and start additional services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ additional_services }}"
  when: additional_services is defined
