---

- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install additional packages
  ansible.builtin.apt:
    name: "{{ additional_packages }}"
    state: present
  when: additional_packages is defined
