---
### ==== Cloudflared Playbook ==== ###
# Adds Cloudflare apt repo and installs cloudflared

- name: Install cloudflared
  hosts: servers
  become: true
  gather_facts: true
  vars:
    ansible_user: "{{ user_devops }}"
    ansible_ssh_private_key_file: "{{ ssh_private_key }}"
    ansible_port: "{{ prod_ssh_port }}"
  roles:
    - role: install-cloudflared
      tags: ['cloudflared']
